CREATE OR REPLACE DATABASE DEV_KARATE_DATA_DB;

USE DATABASE DEV_KARATE_DATA_DB;

CREATE OR REPLACE SCHEMA BURGER_INPUT;
CREATE OR REPLACE SCHEMA BURGER_OUTPUT;

CREATE OR REPLACE TABLE BURGER_INPUT.BREAD (
    CLIENT_ID STRING,
    VALUE STRING
);
CREATE OR REPLACE TABLE BURGER_INPUT.VEGETABLE (
    CLIENT_ID STRING,
    VALUE STRING
);
CREATE OR REPLACE TABLE BURGER_INPUT.MEAT (
    CLIENT_ID STRING,
    VALUE STRING
);
CREATE OR REPLACE TABLE BURGER_OUTPUT.BURGER (
    CLIENT_ID STRING,
    VALUE STRING
);
