direction: right
vars: {
    d2-config: {
      sketch: true
      theme-id: 1 # Neutral gray
    }
}
classes: {
    arrow: {
        style {
            animated: true
        }
    }
    app: {
        shape: image
        icon: https://icons.terrastruct.com/azure%2FCompute%20Service%20Color%2FCloud%20Services%20%28Classic%29.svg
    }
    amqp: {
        shape: image
        icon: ../images/rabbitmq.svg
    }
    kafka: {
        shape: image
        icon: ../images/kafka.svg
    }
    table: {
        shape: cylinder
        icon: ../images/snowflake.png
    }
    title: {
        near: top-left
        shape: text
        style: {
            font-size: 70;
            font-color: "#8B0000"
        }
    }
}
