direction: right
vars: {
    d2-config: {
      sketch: true
      theme-id: 1 # Neutral gray
    }
    component-font-size: 25
    box-font-size: 50
    title-font-size: 70
}
classes: {
    arrow: {
        style {
            animated: true
        }
    }
    app: {
        shape: image
        icon: ../images/app.svg
        style: {
            font-size: ${component-font-size}
        }
    }
    component: {
        style: {
            font-size: ${component-font-size}
        }
    }
    box: {
        style: {
            font-size: ${box-font-size}
        }
    }
    amqp: {
        shape: image
        icon: ../images/rabbitmq.svg
        style: {
            font-size: ${component-font-size}
        }
    }
    kafka: {
        shape: image
        icon: ../images/kafka.svg
        style: {
            font-size: ${component-font-size}
        }
    }
    table: {
        shape: cylinder
        icon: ../images/snowflake.png
        style: {
            font-size: ${component-font-size}
        }
    }
    sql_table: {
        shape: sql_table
        style: {
            font-size: ${component-font-size}
        }
    }
    title: {
        near: top-left
        shape: text
        style: {
            font-size: ${title-font-size};
            font-color: "#8B0000"
        }
    }
}
