direction: right
vars: {
    d2-config: {
      sketch: true
      theme-id: 1 # Neutral gray
    }
    component-font-size: 25
    container-font-size: 40
    box-font-size: 50
    title-font-size: 70
    arrow-font-size: 20
}
classes: {
    arrow: {
        style {
            animated: true
        }
    }
    arrowStream: {
        style {
            animated: true
            font-size: ${arrow-font-size}
        }
        label: "stream"
    }
    arrowBridge: {
        style {
            animated: true
            font-size: ${arrow-font-size}
        }
        label: "bridge"
    }
    app: {
        shape: image
        icon: ../images/app.svg
        style: {
            font-size: ${component-font-size}
        }
    }
    component: {
        style: {
            font-size: ${component-font-size}
        }
    }
    box: {
        style: {
            font-size: ${box-font-size}
        }
    }
    container: {
        style: {
            font-size: ${container-font-size}
            fill: lightcyan
            stroke: darkcyan
            font-color: black
            stroke-width: 8
          }
        icon: https://icons.terrastruct.com/dev%2Fdocker.svg
    }
    amqp: {
        shape: image
        icon: ../images/rabbitmq.svg
        style: {
            font-size: ${component-font-size}
        }
    }
    kafka: {
        shape: image
        icon: ../images/kafka.svg
        style: {
            font-size: ${component-font-size}
        }
    }
    table: {
        shape: cylinder
        icon: ../images/snowflake.png
        style: {
            font-size: ${component-font-size}
        }
    }
    sql_table: {
        shape: sql_table
        style: {
            font-size: ${component-font-size}
        }
    }
    title: {
        near: top-left
        shape: text
        style: {
            font-size: ${title-font-size};
            font-color: "#8B0000"
        }
    }
}
