...@common

Software: { class: app }
DashboardingApp: { class: app }
ELT: { class: title }
Extract.AMQPCollector: { class: amqp }
Extract.RAW: { class: kafka }
Extract.AMQPCollector -> Extract.RAW : { class: arrow }
Extract.RAW  -> Load.Connector : { class: arrow }
Load.Connector -> Load.TableRAW : { class: arrow }
Load.TableRAW: { class: table }
Transform.Task: { 
    shape: rectangle
    class: table 
}
Transform.DBT: {
    shape: image
    icon: ../images/dbt.png
}  
Transform.TableGold: {
    shape: cylinder
    icon: https://companieslogo.com/img/orig/SNOW-35164165.png
}
Load.TableRAW -> Transform.DBT: { class: arrow }
Load.TableRAW -> Transform.Task: { class: arrow }
Transform.DBT -> Transform.TableGold: { class: arrow }
Transform.Task -> Transform.TableGold: { class: arrow }
Transform.TableGold <- DashboardingApp
Software -> Extract.AMQPCollector: { class: arrow }

Test : { near: bottom-center }
  
Test.Karate: {
    shape: image
    icon: ../images/karate.png
}

Test.Karate -> Load.TableRAW: { class: arrow }
Transform.TableGold -> Test.Karate: { class: arrow }