...@common

Cutter: {
    class: component
    shape: image
    icon: ../images/vector.png
}

Software: { class: app }
ETL: { class: title }
Extract: { class: box }
Transform: { class: box }
Load: { class: box }
Test: { class: box }
Transform.KafkaStream: { class : component }
Load.Connector: { class: component }
Extract.HTTPCollector: { class: component }
Extract.AMQPCollector: { class: amqp }
Transform.Input: { class: kafka }
Transform.Output: { class: kafka }
Extract.HTTPCollector -> Transform.Input : { class: arrow }
Extract.AMQPCollector -> Transform.Input : { class: arrow }
Transform.Input -> Transform.KafkaStream : { class: arrow }
Transform.KafkaStream -> Transform.Output : { class: arrow }
Transform.Output -> Load.Connector : { class: arrow }
Load.Connector -> Load.Table : { class: arrow }
  
Load.Table: { class: table }
  
Test : { near: bottom-center }
  
Test.Kapoeira: {
    class: component
    shape: image
    icon: ../images/kapoeira.svg
}

RealTimeApp: {
    class: app
    near: top-center
}

DashboardingApp: {
    class: app
    near: bottom-right
}
  
Test.Kapoeira -> Transform.Input : { class: arrow }
Transform.Output -> Test.Kapoeira : { class: arrow }

Cutter -> Extract.HTTPCollector : { class: arrow }
Software -> Extract.AMQPCollector : { class: arrow }

Transform.Output -> RealTimeApp : { class: arrow }
Load.Table <- DashboardingApp
