...@common
direction: down

docker: {
    class: container
    label: "lectratech/karate-connect:version"
    label.near: outside-top-center
    icon.near: outside-bottom-right
    fatJar: {
        label: "☕ karate-connect-<version>-standalone.jar"
        style: {
            fill: transparent
            font-size: ${component-font-size}
            bold: true
        }
    }
    
    fatJar.karate: {
        shape: image
        icon: ../images/karatelabs.png
        label: "☕ karate.jar"
        style: {
            font-size: ${component-font-size}
        }
    }
    
    fatJar.karate-connect: {
        shape: image
        width: 250
        icon: ../images/lectra.png
        label: "☕ karate-connect.jar\n\n🧩 snowflake, rabbitmq,\nkubernetes, dbt\n(kafka, jdbc, ...)"
        style: {
            font-size: ${component-font-size}
        }
    }
    
    binaries: {
        label: |md
        # <div align="center">🛠️</div>
        
        - 🐍 dbt, snowflake-cli
        - 🐧kubectl
        |
        style: {
            fill: transparent
            font-size: ${component-font-size}
        }
    }
}

docker.fatJar -> docker.binaries : { 
    class: arrow
    label: "calls"
}

docker.style.opacity: 0
docker.fatJar.style.opacity: 0

steps : {
    1: {
        docker.fatJar.style.opacity: 1
    }
    2: {
        docker.style.opacity: 1
    } 
}